import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
  },
  header: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#333',
  },
  subheader: {
    fontSize: 12,
    marginBottom: 10,
    color: '#666',
    textAlign: 'center',
  },
  section: {
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#333',
  },
  row: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  label: {
    width: '30%',
    fontSize: 10,
    fontWeight: 'bold',
    color: '#555',
  },
  value: {
    width: '70%',
    fontSize: 10,
    color: '#333',
  },
  table: {
    width: '100%',
    marginTop: 10,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#007bff',
    color: '#fff',
    padding: 8,
    fontWeight: 'bold',
    fontSize: 10,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    fontSize: 9,
  },
  footer: {
    fontSize: 8,
    color: '#999',
    textAlign: 'center',
    marginTop: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#ddd',
  },
});

export const pdfService = {
  generateTaskReportPDF(tasks, userName) {
    const doc = (
      <Document>
        <Page size="A4" style={styles.page}>
          <Text style={styles.header}>Task Report</Text>
          <Text style={styles.subheader}>Generated for: {userName}</Text>
          <Text style={styles.subheader}>Date: {new Date().toLocaleDateString()}</Text>
          
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Summary</Text>
            <View style={styles.row}>
              <Text style={styles.label}>Total Tasks:</Text>
              <Text style={styles.value}>{tasks.length}</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Completed:</Text>
              <Text style={styles.value}>{tasks.filter(t => t.status === 'completed').length}</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>In Progress:</Text>
              <Text style={styles.value}>{tasks.filter(t => t.status === 'in_progress').length}</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Pending:</Text>
              <Text style={styles.value}>{tasks.filter(t => t.status === 'pending').length}</Text>
            </View>
          </View>
          
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Task Details</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={{ width: '25%' }}>Title</Text>
                <Text style={{ width: '25%' }}>Status</Text>
                <Text style={{ width: '25%' }}>Priority</Text>
                <Text style={{ width: '25%' }}>Due Date</Text>
              </View>
              {tasks.map((task, idx) => (
                <View key={idx} style={styles.tableRow}>
                    <Text style={{ width: '25%' }}>{task.title}</Text>
                    <Text style={{ width: '25%' }}>{task.status}</Text>
                    <Text style={{ width: '25%' }}>{task.priority}</Text>
                    <Text style={{ width: '25%' }}>{task.due_date ? new Date(task.due_date).toLocaleDateString() : 'N/A'}</Text>
                </View>
              ))}
            </View>
          </View>
          
          <Text style={styles.footer}>This report is confidential and generated by SmartTask Management System</Text>
        </Page>
      </Document>
    );
    
    return doc;
  },

  generateAllUsersPDF(users, title = 'User Report') {
    const doc = (
      <Document>
        <Page size="A4" style={styles.page}>
          <Text style={styles.header}>{title}</Text>
          <Text style={styles.subheader}>Date: {new Date().toLocaleDateString()}</Text>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Registered Users</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={{ width: '30%' }}>Name</Text>
                <Text style={{ width: '30%' }}>Email</Text>
                <Text style={{ width: '20%' }}>Role</Text>
                <Text style={{ width: '20%' }}>Status</Text>
              </View>
              {users.map((u, idx) => (
                <View key={idx} style={styles.tableRow}>
                  <Text style={{ width: '30%' }}>{u.full_name}</Text>
                  <Text style={{ width: '30%' }}>{u.email}</Text>
                  <Text style={{ width: '20%' }}>{u.role}</Text>
                  <Text style={{ width: '20%' }}>{u.status}</Text>
                </View>
              ))}
            </View>
          </View>

          <Text style={styles.footer}>Generated by SmartTask Management System</Text>
        </Page>
      </Document>
    );

    return doc;
  },

  generateAnalyticsReportPDF(metrics, title = 'Analytics Report') {
    const doc = (
      <Document>
        <Page size="A4" style={styles.page}>
          <Text style={styles.header}>{title}</Text>
          <Text style={styles.subheader}>Date: {new Date().toLocaleDateString()}</Text>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>System Metrics</Text>
            <View style={styles.row}><Text style={styles.label}>Total Tasks:</Text><Text style={styles.value}>{metrics.totalTasks}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Completed:</Text><Text style={styles.value}>{metrics.completedCount}</Text></View>
            <View style={styles.row}><Text style={styles.label}>In Progress:</Text><Text style={styles.value}>{metrics.inProgressCount}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Pending:</Text><Text style={styles.value}>{metrics.pendingCount}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Completion Rate:</Text><Text style={styles.value}>{metrics.completionRate}%</Text></View>
            <View style={styles.row}><Text style={styles.label}>Total Users:</Text><Text style={styles.value}>{metrics.totalUsers}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Average Tasks/User:</Text><Text style={styles.value}>{metrics.averageTasksPerUser}</Text></View>
          </View>

          <Text style={styles.footer}>Generated by SmartTask Management System</Text>
        </Page>
      </Document>
    );

    return doc;
  },

  generateActivityReportPDF({ tasks = [], notifications = [] }, title = 'Activity Report') {
    const doc = (
      <Document>
        <Page size="A4" style={styles.page}>
          <Text style={styles.header}>{title}</Text>
          <Text style={styles.subheader}>Date: {new Date().toLocaleDateString()}</Text>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Recent Tasks</Text>
            {tasks.slice(0, 20).map((t, i) => (
              <View key={i} style={styles.row}>
                <Text style={{ width: '40%', fontSize: 10 }}>{t.title}</Text>
                <Text style={{ width: '20%', fontSize: 10 }}>{t.status}</Text>
                <Text style={{ width: '40%', fontSize: 10 }}>{t.updated_at ? new Date(t.updated_at).toLocaleString() : (t.created_at ? new Date(t.created_at).toLocaleString() : '')}</Text>
              </View>
            ))}
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Recent Notifications</Text>
            {notifications.slice(0, 30).map((n, i) => (
              <View key={i} style={styles.row}>
                <Text style={{ width: '20%', fontSize: 10 }}>{n.type}</Text>
                <Text style={{ width: '60%', fontSize: 10 }}>{n.message}</Text>
                <Text style={{ width: '20%', fontSize: 10 }}>{n.created_at ? new Date(n.created_at).toLocaleString() : ''}</Text>
              </View>
            ))}
          </View>

          <Text style={styles.footer}>Generated by SmartTask Management System</Text>
        </Page>
      </Document>
    );

    return doc;
  },

  async downloadDocument(docElement, filename = 'report.pdf') {
    try {
      const asPdf = pdf(docElement);
      const blob = await asPdf.toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('❌ Error downloading PDF document:', err);
      throw err;
    }
  },

  generateCustomReportPDF(reportTitle, sections) {
    const doc = (
      <Document>
        <Page size="A4" style={styles.page}>
          <Text style={styles.header}>{reportTitle}</Text>
          <Text style={styles.subheader}>Date: {new Date().toLocaleDateString()}</Text>
          
          {sections.map((section, idx) => (
            <View key={idx} style={styles.section}>
              <Text style={styles.sectionTitle}>{section.title}</Text>
              {Array.isArray(section.content) ? (
                section.content.map((item, itemIdx) => (
                  <Text key={itemIdx} style={{ fontSize: 10, marginBottom: 5, color: '#333' }}>
                    • {item}
                  </Text>
                ))
              ) : (
                <Text style={{ fontSize: 10, color: '#333' }}>{section.content}</Text>
              )}
            </View>
          ))}
          
          <Text style={styles.footer}>Generated by SmartTask Management System</Text>
        </Page>
      </Document>
    );
    
    return doc;
  },
};

export default pdfService;